[tableOfContents]
  startLevel = 1
  endLevel = 3 # 不包含 endLevel，所以只显示 1-2 级别。
showTableOfContents = true

[module.hugoVersion]
extended = true
min = "0.87.0"
max = "0.140.2"

[markup.goldmark.parser]
  attribute = true
  autoHeadingID = false
  wrapStandAloneImageWithinParagraph = false
  [markup.goldmark.renderer]
    unsafe = true

[params]
  articleWidth = "full"  # 可选值包括：default, wide, full